# Solo para datos sensibles como usuario, contraseña, etc.
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USER: "postgres.uhryusinmvtkjteivdre"
  DB_PASSWORD: "RYWd1MO5PpNIBHKV"